export const TOGGLE_TRANSFERS_FILTER = "TOGGLE_TRANSFERS_FILTER";
export const CHANGE_CURRENT_CURRENCY = "CHANGE_CURRENT_CURRENCY";

export const TICKETS_FETCH_REQUEST = "TICKETS_FETCH_REQUEST";
export const TICKETS_FETCH_SUCCESS = "TICKETS_FETCH_SUCCESS";
export const TICKETS_FETCH_FAIL = "TICKETS_FETCH_FAIL";
